spring:
  jpa:
    open-in-view: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./task-tracker-database
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  servlet:
    context-path: /api/generation
