spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  servlet:
    context-path: /api/generation

generation:
  gitlab:
    # group of base repository: divided for tests
    base-group: code
    # group in which to create repositories with generated code
    target-group: code-test
    host: https://clickndrest.gitlab.yandexcloud.net
    base-repository: base-application-for-generation
    base-branch: main
    root-package-path: base-crud-app/src/main/java/com/github/click/nd/rest/base
    token: glpat-KsNbibF3WTKYa85jN2Hc
